// Listen for messages from web pages (localhost or app.oppaclip.click)
chrome.runtime.onMessageExternal.addListener(
  (request, sender, sendResponse) => {
    if (request.method === "getCookies") {
      
      chrome.cookies.getAll({domain: "youtube.com"}, (cookies) => {
        if (!cookies || cookies.length === 0) {
          sendResponse({success: false, error: "No YouTube cookies found. Please log in to YouTube."});
          return;
        }

        let content = "# Netscape HTTP Cookie File\n";
        content += "# This file is generated by OppaClip Helper. Do not edit.\n\n";

        cookies.forEach((cookie) => {
          // Format: domain flag path secure expiration name value
          const domain = cookie.domain;
          const flag = domain.startsWith('.') ? "TRUE" : "FALSE";
          const path = cookie.path;
          const secure = cookie.secure ? "TRUE" : "FALSE";
          const expiration = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
          const name = cookie.name;
          const value = cookie.value;

          content += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
        });

        sendResponse({success: true, content: content});
      });

      // Return true to indicate we will send a response asynchronously
      return true; 
    }
  }
);
