document.getElementById('downloadBtn').addEventListener('click', () => {
  chrome.tabs.query({active: true, currentWindow: true}, (tabs) => {
    // We target youtube.com specifically
    chrome.cookies.getAll({domain: "youtube.com"}, (cookies) => {
      if (!cookies || cookies.length === 0) {
        alert("No YouTube cookies found! Please ensure you are on youtube.com and logged in.");
        return;
      }

      let content = "# Netscape HTTP Cookie File\n";
      content += "# This file is generated by OppaClip Helper.  Do not edit.\n\n";

      cookies.forEach((cookie) => {
        // Format: domain flag path secure expiration name value
        const domain = cookie.domain;
        const flag = domain.startsWith('.') ? "TRUE" : "FALSE";
        const path = cookie.path;
        const secure = cookie.secure ? "TRUE" : "FALSE";
        const expiration = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
        const name = cookie.name;
        const value = cookie.value;

        content += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
      });

      downloadFile(content, "cookies.txt");
    });
  });
});

function downloadFile(content, filename) {
  const blob = new Blob([content], {type: 'text/plain'});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
